<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
      <LangVersion>latest</LangVersion>
      <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ModInfo\**" />
    <EmbeddedResource Remove="ModInfo\**" />
    <None Remove="ModInfo\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\WreathBack.png" />
    <None Remove="Resources\WreathFront.png" />
    <None Remove="Resources\WreathLocked.png" />
    <None Remove="Resources\WreathOW.png" />
    <None Remove="Resources\WreathUnlocked.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\WreathBack.png" />
    <EmbeddedResource Include="Resources\WreathFront.png" />
    <EmbeddedResource Include="Resources\WreathLocked.png" />
    <EmbeddedResource Include="Resources\WreathOW.png" />
    <EmbeddedResource Include="Resources\WreathUnlocked.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="UnityEngine.Modules" Version="2020.3.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>compile</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\References\BrutalOrchestra\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BrutalAPI">
      <HintPath>..\Pentacle\bin\Release\netstandard2.0\BrutalAPI.dll</HintPath>
    </Reference>
    <Reference Include="Grimoire">
      <HintPath>..\Grimoire\bin\Debug\netstandard2.0\Grimoire.dll</HintPath>
    </Reference>
    <Reference Include="Pentacle">
      <HintPath>..\Pentacle\bin\Debug\netstandard2.0\Pentacle.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
