<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
      <LangVersion>latest</LangVersion>
      <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AssetBundle\**" />
    <Compile Remove="ModInfo\**" />
    <EmbeddedResource Remove="AssetBundle\**" />
    <EmbeddedResource Remove="ModInfo\**" />
    <None Remove="AssetBundle\**" />
    <None Remove="ModInfo\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Items\Item19.png" />
    <None Remove="Resources\Items\OldBleach.png" />
    <None Remove="Resources\Items\TrueZeal.png" />
    <None Remove="Resources\WreathBack.png" />
    <None Remove="Resources\WreathFront.png" />
    <None Remove="Resources\WreathLocked.png" />
    <None Remove="Resources\WreathOW.png" />
    <None Remove="Resources\WreathUnlocked.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Characters\Wreath\WreathBack.png" />
    <EmbeddedResource Include="Resources\Characters\Wreath\WreathFront.png" />
    <EmbeddedResource Include="Resources\Characters\Wreath\WreathLocked.png" />
    <EmbeddedResource Include="Resources\Characters\Wreath\WreathOW.png" />
    <EmbeddedResource Include="Resources\Characters\Wreath\WreathUnlocked.png" />
    <EmbeddedResource Include="Resources\Items\Item19.png" />
    <EmbeddedResource Include="Resources\Items\OldBleach.png" />
    <EmbeddedResource Include="Resources\Items\TrueZeal.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="UnityEngine.Modules" Version="2020.3.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>compile</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\References\BrutalOrchestra\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BrutalAPI">
      <HintPath>..\Pentacle\bin\Release\netstandard2.0\BrutalAPI.dll</HintPath>
    </Reference>
    <Reference Include="Grimoire">
      <HintPath>..\Grimoire\bin\Debug\netstandard2.0\Grimoire.dll</HintPath>
    </Reference>
    <Reference Include="Pentacle">
      <HintPath>..\Pentacle\bin\Debug\netstandard2.0\Pentacle.dll</HintPath>
    </Reference>
    <Reference Include="YarnSpinner">
      <HintPath>..\References\Unity\YarnSpinner.dll</HintPath>
    </Reference>
    <Reference Include="YarnSpinner.Compiler">
      <HintPath>..\References\Unity\YarnSpinner.Compiler.dll</HintPath>
    </Reference>
    <Reference Include="YarnSpinner.Unity">
      <HintPath>..\References\Unity\YarnSpinner.Unity.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="AssetBundle\AssetBundles\157fools" />
  </ItemGroup>

</Project>
